### ISSUE TITLE
Some minor issues with Reset KrbTgt Password script

### ISSUE THREAD

**Issue by paulhey** [zjorz/Public-AD-Scripts#4]
In the process of auditing this script for use in our environment I found I couple of issues that I've submitted fixes for in #3 
One is just using the automatic variable `$PWD` during password generation, which could lead to some rather bizarre results.
The other is just a typo in using a variable in a single-quoted string instead of a double-quoted string.

**Comment by zjorz** [comment]
Hi,
can you please point out which is "The other is just a typo in using a variable in a single-quoted string instead of a double-quoted string."?
Thanks

**Comment by zjorz** [comment]
never mind, found it

**Comment by zjorz** [comment]
thanks for the feedback. Adding your fixes. Working on processing feedback from different people
