### ISSUE TITLE
Issues when reseting the password.

### ISSUE THREAD

**Issue by cheapscotman** [zjorz/Public-AD-Scripts#5]
I have tried this version and password reset fails fails Exception Message...: The password does not meet the length, complexity, or history requirement of the domain. It uses 64 characters for the new password.  I can do all the other functions of resetting the password on the bogus krbtgt account.  I can manually change it via ASAP or I use a older script https://gist.github.com/mubix/fd0c89ec021f70023695

**Comment by zjorz** [comment]
Could you please provide more detailed info if what you were doing and against which account, and what you had done before this error popped up?
Can you also provide the state (all attributes) of the object?

Please also provide the original error message 

The password is really long, and unique. A password reset is always possible
