### ISSUE TITLE
Script doesn't recognize that user is member or domain admins group

### ISSUE THREAD

**Issue by ArrowheadAdmin1** [zjorz/Public-AD-Scripts#7]
I'm running the script with an account that is a member of domain and enterprise admins groups but the it errors out stating that the account isn't a member of those groups.

**Comment by zjorz** [comment]
Can you do please provide more info?
• Which version of the script
• with or without uac enabled
• running on srv or dc?
• local or remote forest
• in case remote, perms over trust or explicit creds
• which modes of the script
• anything else important or specific to your env

**Comment by bgregorcy** [comment]
I am getting the same thing.  
DC' s are 2022
I disabled UAC on the domain controller 
Run from DC
Mode 1

**Comment by bgregorcy** [comment]
I enabled Active Directory Web Services on the DC and it works now.

**Comment by DiPersiaTech** [comment]
Same problem for one environment I handle.  I found that (even with UAC fully disabled), Powershell was not running as an admin.  Ran as admin, runs fine.

**Comment by zjorz** [comment]
Latest version contains fix to this as the web service is not used anymore
